spring:
  application:
    name: auth-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: miusuario
    password: '2304'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    #hibernate:
      #ddl-auto: update
    show-sql: true

server:
  port: 8081
  servlet:
   context-path: /api/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        amqp: DEBUG
        messaging: DEBUG
